INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Bulbasaur',69,308,15);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Ivysaur',130,399,8);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Venusaur',1000,396,2);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Charmander',85,18,1);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Charmeleon',190,86,5);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Charizard',905,372,5);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Squirtle',90,346,6);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Wartortle',225,335,4);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Blastoise',855,31,15);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Caterpie',29,308,19);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Metapod',99,349,12);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Butterfree',320,15,2);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Weedle',32,132,19);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Kakuna',100,36,18);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Beedrill',295,316,17);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Pidgey',18,310,6);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Pidgeotto',300,325,7);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Pidgeot',395,98,10);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Rattata',35,204,9);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Raticate',185,496,15);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Spearow',20,373,19);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Fearow',380,256,1);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Ekans',69,322,12);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Arbok',650,462,10);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Pikachu',60,418,13);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Raichu',300,416,3);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Sandshrew',120,323,8);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Sandslash',295,269,8);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Nidoran-f',70,395,3);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Nidorina',200,86,9);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Nidoqueen',600,111,11);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Nidoran-m',90,32,10);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Nidorino',195,323,5);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Nidoking',620,285,18);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Clefairy',75,445,4);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Clefable',400,231,11);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Vulpix',99,15,15);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Ninetales',199,276,18);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Jigglypuff',55,37,0);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Wigglytuff',120,345,15);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Zubat',75,350,5);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Golbat',550,14,9);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Oddish',54,170,7);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Gloom',86,7,5);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Vileplume',186,431,8);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Paras',54,206,19);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Parasect',295,160,3);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Venonat',300,240,16);
INSERT INTO Produtos( `nome`, `peso`, `preco`, `qtd_estoque`) VALUES ('Venomoth',125,465,8);

INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/1.png',1);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/1.png',1);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png',1);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/2.png',2);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/2.png',2);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png',2);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/3.png',3);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/3.png',3);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/3.png',3);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/3.png',3);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png',3);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/4.png',4);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/4.png',4);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png',4);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/5.png',5);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/5.png',5);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png',5);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/6.png',6);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/6.png',6);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png',6);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/7.png',7);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/7.png',7);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png',7);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/8.png',8);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/8.png',8);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png',8);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/9.png',9);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/9.png',9);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png',9);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/10.png',10);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/10.png',10);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png',10);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/11.png',11);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/11.png',11);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png',11);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/12.png',12);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/12.png',12);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/12.png',12);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/12.png',12);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png',12);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/13.png',13);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/13.png',13);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png',13);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/14.png',14);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/14.png',14);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png',14);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/15.png',15);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/15.png',15);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png',15);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/16.png',16);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/16.png',16);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png',16);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/17.png',17);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/17.png',17);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png',17);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/18.png',18);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/18.png',18);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png',18);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/19.png',19);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/19.png',19);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/19.png',19);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/19.png',19);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png',19);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/20.png',20);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/20.png',20);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/20.png',20);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/20.png',20);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png',20);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/21.png',21);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/21.png',21);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/21.png',21);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/22.png',22);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/22.png',22);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/22.png',22);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/23.png',23);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/23.png',23);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/23.png',23);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/24.png',24);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/24.png',24);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/24.png',24);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/25.png',25);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/25.png',25);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/25.png',25);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/25.png',25);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/25.png',25);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/26.png',26);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/26.png',26);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/26.png',26);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/26.png',26);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/26.png',26);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/27.png',27);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/27.png',27);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/27.png',27);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/28.png',28);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/28.png',28);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/28.png',28);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/29.png',29);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/29.png',29);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/29.png',29);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/30.png',30);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/30.png',30);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/30.png',30);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/31.png',31);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/31.png',31);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/31.png',31);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/32.png',32);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/32.png',32);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/32.png',32);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/33.png',33);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/33.png',33);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/33.png',33);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/34.png',34);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/34.png',34);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/34.png',34);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/35.png',35);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/35.png',35);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/35.png',35);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/36.png',36);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/36.png',36);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/36.png',36);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/37.png',37);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/37.png',37);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/37.png',37);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/38.png',38);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/38.png',38);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/38.png',38);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/39.png',39);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/39.png',39);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/39.png',39);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/40.png',40);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/40.png',40);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/40.png',40);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/41.png',41);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/41.png',41);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/41.png',41);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/41.png',41);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/41.png',41);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/42.png',42);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/42.png',42);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/42.png',42);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/43.png',43);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/43.png',43);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/43.png',43);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/44.png',44);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/44.png',44);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/44.png',44);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/44.png',44);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/44.png',44);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/45.png',45);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/female/45.png',45);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/45.png',45);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/female/45.png',45);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/45.png',45);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/46.png',46);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/46.png',46);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/46.png',46);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/47.png',47);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/47.png',47);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/47.png',47);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/48.png',48);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/48.png',48);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/48.png',48);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/49.png',49);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/back/shiny/49.png',49);
INSERT INTO Imagens_produto(`link`, `fk_produto_id`) VALUES ('https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/49.png',49);

INSERT INTO Formas_pagamento(`descricao`) VALUES ('À vista');
INSERT INTO Formas_pagamento(`descricao`) VALUES ('Crédito');
INSERT INTO Formas_pagamento(`descricao`) VALUES ('Débito');
